### ISSUE TITLE
How to specify schema to sync with?

### ISSUE THREAD

**Issue by jifeon** [mystand/pgcodebase#1]
Hi! Thx for patching pgrebase behaviour re dependencies!

I have 2 schemas and therefore 2 folders to sync with. I do not have `public` schema. So my question is how to specify which schema pgcodebase should use? Currently I get this error:

```
yarn pgcodebase
yarn run v1.6.0
$ npx pgcodebase -u postgres -p password -d adara_crm -D ./src/api/sql/adara_crm
{ error: no schema has been selected to create in
    at Connection.parseE (/Users/jifeon/projects/adara-crm-api/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/Users/jifeon/projects/adara-crm-api/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/Users/jifeon/projects/adara-crm-api/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
  name: 'error',
  length: 120,
  severity: 'ERROR',
  code: '3F000',
  detail: undefined,
  hint: undefined,
  position: '28',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '473',
  routine: 'RangeVarGetCreationNamespace' }
```

**Comment by ReFruity** [comment]
Thank you for taking your time to make a PR, I merged it and will also update README shortly
